### ISSUE TITLE
Java Reflections are trash

### ISSUE THREAD

**Issue by noahzemlin** [DylanSMR/DiscadeBot#1]
Java Reflections are used [every time DiscadeBot receives a message](https://github.com/DylanSMR/DiscadeBot/blob/a70b1962fb235fc9127a021e73432054660ff096/src/main/java/Discord/DiscordEventHandler.java#L14-L26), which has crazy poor performance. I'd recommend only using Java Reflections once during the bot initialization to gather all of the commands and then store them in an array or dictionary to use during your command lookup. Alternatively, not using Reflections at all would probably be the best but require by-hand initialization of all the commands or some fancy use of [static blocks](https://www.geeksforgeeks.org/g-fact-79/).

**Comment by DylanSMR** [comment]
Used a little bit of both static blocks and by-hand in a way, thank you!
